export {default as Home} from './Home'
export {default as Katalok} from './Katalok'
export {default as About} from './About'
export {default as News} from './News'
export {default as Contact} from './Contact'
export {default as SingleCar} from './SingleCar'